Toolbar & headline section
xJokeer/portfolio pull request #2
Opened 2021-07-08 19:36 UTC by xJokeer

### Toolbar and Headline section 😬

>Open pull request to check for issues😴

>Waiting for approbation to pull my codes to my main branch😎😎😎😎

2021-07-08 22:53 UTC, xJokeer commented
### Hey there!😁

After several attempts🙄, all errors have been corrected🥳🥳🥳.

Can you check this?
can I merge my pull request?
------

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments

2021-07-08 23:48 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 23:48 UTC, arslanbisharat commented on index.html
> +        <nav class="nav-bar">
-  [ ] Please make sure you are using header tag.

2021-07-08 23:48 UTC, arslanbisharat commented on index.html
> +                <h4 class="carlosfeliz">Carlos Feliz</h4>
Lolo should be a link and encloswd in a tag

2021-07-08 23:48 UTC, arslanbisharat commented on index.html
> +    <header class="main">
Instead of header please use section tag

2021-07-08 23:48 UTC, arslanbisharat commented on index.html
> +                    </div>
You should use ul and li tags

2021-07-08 23:48 UTC, arslanbisharat commented on index.html
> +                        </div>
You should use ul and li tags

2021-07-09 00:13 UTC, xJokeer commented on index.html
> +                    </div>
They should have inside an `<a>`?

2021-07-09 00:14 UTC, xJokeer commented on index.html
> +                    </div>
Or I'll add that after this time?

2021-07-09 00:52 UTC, xJokeer commented on index.html
> +                <h4 class="carlosfeliz">Carlos Feliz</h4>
Like a random one?? cause I don't have a logo.
What should I do in this case?

2021-07-09 01:07 UTC, xJokeer commented
##Update tags😎

- Add header instead of div.😉
- Add ul and li . (¬‿¬)
- Add section instead of header. 😅
- remove some issues and commit my changes. 🤐🤐
- Add an anchor to my logo as that way now is a link. 😬😬😬 

In case it is necessary to add a logo
--------

> while working on my portfolio, i will work on a logo with my name

> I would have to create my own logo, I don't want to use a random one. 

> I think I have fixed all the errors that I had previously been given.

2021-07-09 01:35 UTC, voscarmv approved these changes
Hi @xJokeer , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 01:39 UTC, merged