Version web RWD
xJokeer/portfolio pull request #5
Opened 2021-07-16 19:04 UTC by xJokeer

### Hey there! 😋

**This is my web version for the temple 4**

2021-07-16 19:07 UTC, Shaher-11 reviewed
## _Status:_ Invalid:no_entry::no_entry::no_entry:
### Hello @xJokeer,
This Code Review Request will be marked as invalid in your dashboard because the GitHub linter checks are not passing as required for this project.
Please make the necessary changes and submit another code review request once you are ready! :smiley: :smiley:

2021-07-16 21:03 UTC, Emmyn5600 requested changes
## STATUS: Changes Requested :recycle:

Hi @xJokeer 

Good job so far!:clap::clap:
You have done well in implementing the project requirements :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

##  Required Changes:writing_hand:

* Please add the live link demo in your Readme file.
* Write a descriptive PR explaining in detail what you have done in your project. 
* You need to make more commits in your projects instead of pushing all changes at once

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-16 21:03 UTC, Emmyn5600 commented on css/styles.css
> +  }
- [x] Kindly, Refer to the figma to fix the following issues, as you see there is a difference with yours and original. Please work on it to look the same.

              --------------------------------------------Original-------------------------------

![desk](https://user-images.githubusercontent.com/55635977/126006898-a024abc3-cbf0-4df6-b143-b96b14777034.png)

              -----------------------------------------Yours----------------------------------------

![yodesk](https://user-images.githubusercontent.com/55635977/126006908-84cfd072-9fbc-4d72-a7db-6cd123e71d00.png)

2021-07-16 21:03 UTC, Emmyn5600 commented on index.html
> +                </li>
- [x] Kindly, align the social icons in the properly way.

   --------------------------- Original ------------------------------------
![workdesk](https://user-images.githubusercontent.com/55635977/126007371-6401edb7-05c3-471d-bbc3-5116e29cd1cc.png)


  --------------------------- Yours ------------------------------------
![workdesk1](https://user-images.githubusercontent.com/55635977/126007396-5999e23c-35b7-46e5-aa2f-a95b9739bb2c.png)

2021-07-16 21:03 UTC, Emmyn5600 commented on index.html
> +            </section>
- [x] Please refer to the template to fix the issue.

---------------------------------- Original -----------------------------
![contactdesk](https://user-images.githubusercontent.com/55635977/126007774-2b564ca7-72f8-48d6-a8e5-3111ee93fd31.png)

---------------------------------- Yours-----------------------------
![contactdesk1](https://user-images.githubusercontent.com/55635977/126007781-aa4e9f75-faeb-41f1-bf05-1fcddb1720c7.png)

2021-07-17 01:07 UTC, george-swift approved these changes
## Approved 🚢 

Hello Elim 👋🏽 , 

Great job largely implementing the changes required by the previous reviewer. Your commits were more descriptive as well. Congratulations! 🎉  Your project is approved. However, there is still room for improvement. 

[OPTIONAL]
- Kindly try to replicate project-specific requirements as much as possible.
- As requested earlier, kindly add a live link to your README.
I also strongly recommend you consider the optional suggestion in my comment below.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-17 01:07 UTC, george-swift commented on index.html
> +            </p>
- [ ] [OPTIONAL]
You could use the `max-width` property on this `p` tag to fully replicate the width defined on Figma. Since the content is larger than the maximum width, it will automatically change the height of the element.

2021-07-17 03:08 UTC, merged